/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.19.0-SNAPSHOT).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.api;

import org.openapitools.model.AccountRequest;
import org.openapitools.model.AccountResponse;
import org.openapitools.model.AccountUpdateRequest;
import org.openapitools.model.ErrorResponse;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.ExampleObject;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.multipart.MultipartFile;
import org.springframework.web.server.ServerWebExchange;
import reactor.core.publisher.Flux;
import reactor.core.publisher.Mono;
import org.springframework.http.codec.multipart.Part;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2026-01-07T05:45:55.296827463Z[Etc/UTC]", comments = "Generator version: 7.19.0-SNAPSHOT")
@Validated
@Tag(name = "Accounts", description = "Bank account management")
public interface AccountsApi {

    String PATH_CREATE_ACCOUNT = "/api/v1/customers/{customerId}/accounts";
    /**
     * POST /api/v1/customers/{customerId}/accounts : Create a new account for a customer
     *
     * @param customerId  (required)
     * @param accountRequest  (required)
     * @return Account created successfully (status code 201)
     *         or Customer not found (status code 404)
     */
    @Operation(
        operationId = "createAccount",
        summary = "Create a new account for a customer",
        tags = { "Accounts" },
        responses = {
            @ApiResponse(responseCode = "201", description = "Account created successfully", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = AccountResponse.class))
            }),
            @ApiResponse(responseCode = "404", description = "Customer not found", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = AccountsApi.PATH_CREATE_ACCOUNT,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default Mono<ResponseEntity<AccountResponse>> createAccount(
        @NotNull @Parameter(name = "customerId", description = "", required = true, in = ParameterIn.PATH) @PathVariable("customerId") String customerId,
        @Parameter(name = "AccountRequest", description = "", required = true) @Valid @RequestBody Mono<AccountRequest> accountRequest,
        @Parameter(hidden = true) final ServerWebExchange exchange
    ) {
        Mono<Void> result = Mono.empty();
        exchange.getResponse().setStatusCode(HttpStatus.NOT_IMPLEMENTED);
        for (MediaType mediaType : exchange.getRequest().getHeaders().getAccept()) {
            if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                String exampleString = "{ \"createdAt\" : \"2000-01-23T04:56:07.000+00:00\", \"balance\" : 1200.5, \"accountType\" : \"SAVINGS\", \"customerId\" : \"c123\", \"id\" : \"a123\", \"status\" : true }";
                result = ApiUtil.getExampleResponse(exchange, MediaType.valueOf("application/json"), exampleString);
                break;
            }
            if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                String exampleString = "{ \"code\" : \"RESOURCE_NOT_FOUND\", \"message\" : \"Resource not found\", \"timestamp\" : \"2000-01-23T04:56:07.000+00:00\" }";
                result = ApiUtil.getExampleResponse(exchange, MediaType.valueOf("application/json"), exampleString);
                break;
            }
        }
        return result.then(accountRequest).then(Mono.empty());

    }


    String PATH_DELETE_ACCOUNT = "/api/v1/accounts/{accountId}";
    /**
     * DELETE /api/v1/accounts/{accountId} : Close account
     *
     * @param accountId  (required)
     * @return Account closed successfully (status code 204)
     */
    @Operation(
        operationId = "deleteAccount",
        summary = "Close account",
        tags = { "Accounts" },
        responses = {
            @ApiResponse(responseCode = "204", description = "Account closed successfully")
        }
    )
    @RequestMapping(
        method = RequestMethod.DELETE,
        value = AccountsApi.PATH_DELETE_ACCOUNT
    )
    default Mono<ResponseEntity<Void>> deleteAccount(
        @NotNull @Parameter(name = "accountId", description = "", required = true, in = ParameterIn.PATH) @PathVariable("accountId") String accountId,
        @Parameter(hidden = true) final ServerWebExchange exchange
    ) {
        Mono<Void> result = Mono.empty();
        exchange.getResponse().setStatusCode(HttpStatus.NOT_IMPLEMENTED);
        return result.then(Mono.empty());

    }


    String PATH_GET_ACCOUNT_BY_ID = "/api/v1/accounts/{accountId}";
    /**
     * GET /api/v1/accounts/{accountId} : Get account by ID
     *
     * @param accountId  (required)
     * @return Account found (status code 200)
     *         or Account not found (status code 404)
     */
    @Operation(
        operationId = "getAccountById",
        summary = "Get account by ID",
        tags = { "Accounts" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Account found", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = AccountResponse.class))
            }),
            @ApiResponse(responseCode = "404", description = "Account not found", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = AccountsApi.PATH_GET_ACCOUNT_BY_ID,
        produces = { "application/json" }
    )
    default Mono<ResponseEntity<AccountResponse>> getAccountById(
        @NotNull @Parameter(name = "accountId", description = "", required = true, in = ParameterIn.PATH) @PathVariable("accountId") String accountId,
        @Parameter(hidden = true) final ServerWebExchange exchange
    ) {
        Mono<Void> result = Mono.empty();
        exchange.getResponse().setStatusCode(HttpStatus.NOT_IMPLEMENTED);
        for (MediaType mediaType : exchange.getRequest().getHeaders().getAccept()) {
            if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                String exampleString = "{ \"createdAt\" : \"2000-01-23T04:56:07.000+00:00\", \"balance\" : 1200.5, \"accountType\" : \"SAVINGS\", \"customerId\" : \"c123\", \"id\" : \"a123\", \"status\" : true }";
                result = ApiUtil.getExampleResponse(exchange, MediaType.valueOf("application/json"), exampleString);
                break;
            }
            if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                String exampleString = "{ \"code\" : \"RESOURCE_NOT_FOUND\", \"message\" : \"Resource not found\", \"timestamp\" : \"2000-01-23T04:56:07.000+00:00\" }";
                result = ApiUtil.getExampleResponse(exchange, MediaType.valueOf("application/json"), exampleString);
                break;
            }
        }
        return result.then(Mono.empty());

    }


    String PATH_GET_ACCOUNTS_BY_CUSTOMER = "/api/v1/customers/{customerId}/accounts";
    /**
     * GET /api/v1/customers/{customerId}/accounts : Get all accounts for a customer
     *
     * @param customerId  (required)
     * @return List of accounts (status code 200)
     */
    @Operation(
        operationId = "getAccountsByCustomer",
        summary = "Get all accounts for a customer",
        tags = { "Accounts" },
        responses = {
            @ApiResponse(responseCode = "200", description = "List of accounts", content = {
                @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = AccountResponse.class)))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = AccountsApi.PATH_GET_ACCOUNTS_BY_CUSTOMER,
        produces = { "application/json" }
    )
    default Mono<ResponseEntity<Flux<AccountResponse>>> getAccountsByCustomer(
        @NotNull @Parameter(name = "customerId", description = "", required = true, in = ParameterIn.PATH) @PathVariable("customerId") String customerId,
        @Parameter(hidden = true) final ServerWebExchange exchange
    ) {
        Mono<Void> result = Mono.empty();
        exchange.getResponse().setStatusCode(HttpStatus.NOT_IMPLEMENTED);
        for (MediaType mediaType : exchange.getRequest().getHeaders().getAccept()) {
            if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                String exampleString = "[ { \"createdAt\" : \"2000-01-23T04:56:07.000+00:00\", \"balance\" : 1200.5, \"accountType\" : \"SAVINGS\", \"customerId\" : \"c123\", \"id\" : \"a123\", \"status\" : true }, { \"createdAt\" : \"2000-01-23T04:56:07.000+00:00\", \"balance\" : 1200.5, \"accountType\" : \"SAVINGS\", \"customerId\" : \"c123\", \"id\" : \"a123\", \"status\" : true } ]";
                result = ApiUtil.getExampleResponse(exchange, MediaType.valueOf("application/json"), exampleString);
                break;
            }
        }
        return result.then(Mono.empty());

    }


    String PATH_UPDATE_ACCOUNT = "/api/v1/accounts/{accountId}";
    /**
     * PUT /api/v1/accounts/{accountId} : Update account status
     *
     * @param accountId  (required)
     * @param accountUpdateRequest  (required)
     * @return Account updated (status code 200)
     */
    @Operation(
        operationId = "updateAccount",
        summary = "Update account status",
        tags = { "Accounts" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Account updated", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = AccountResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.PUT,
        value = AccountsApi.PATH_UPDATE_ACCOUNT,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default Mono<ResponseEntity<AccountResponse>> updateAccount(
        @NotNull @Parameter(name = "accountId", description = "", required = true, in = ParameterIn.PATH) @PathVariable("accountId") String accountId,
        @Parameter(name = "AccountUpdateRequest", description = "", required = true) @Valid @RequestBody Mono<AccountUpdateRequest> accountUpdateRequest,
        @Parameter(hidden = true) final ServerWebExchange exchange
    ) {
        Mono<Void> result = Mono.empty();
        exchange.getResponse().setStatusCode(HttpStatus.NOT_IMPLEMENTED);
        for (MediaType mediaType : exchange.getRequest().getHeaders().getAccept()) {
            if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                String exampleString = "{ \"createdAt\" : \"2000-01-23T04:56:07.000+00:00\", \"balance\" : 1200.5, \"accountType\" : \"SAVINGS\", \"customerId\" : \"c123\", \"id\" : \"a123\", \"status\" : true }";
                result = ApiUtil.getExampleResponse(exchange, MediaType.valueOf("application/json"), exampleString);
                break;
            }
        }
        return result.then(accountUpdateRequest).then(Mono.empty());

    }

}
