/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.19.0-SNAPSHOT).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.api;

import org.openapitools.model.CustomerRequest;
import org.openapitools.model.CustomerResponse;
import org.openapitools.model.ErrorResponse;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.ExampleObject;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.multipart.MultipartFile;
import org.springframework.web.server.ServerWebExchange;
import reactor.core.publisher.Flux;
import reactor.core.publisher.Mono;
import org.springframework.http.codec.multipart.Part;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2026-01-07T05:45:55.296827463Z[Etc/UTC]", comments = "Generator version: 7.19.0-SNAPSHOT")
@Validated
@Tag(name = "Customers", description = "Customer management operations")
public interface CustomersApi {

    String PATH_CREATE_CUSTOMER = "/api/v1/customers";
    /**
     * POST /api/v1/customers : Create a new customer
     *
     * @param customerRequest  (required)
     * @return Customer created successfully (status code 201)
     *         or Invalid request (status code 400)
     *         or Customer already exists (status code 409)
     */
    @Operation(
        operationId = "createCustomer",
        summary = "Create a new customer",
        tags = { "Customers" },
        responses = {
            @ApiResponse(responseCode = "201", description = "Customer created successfully", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = CustomerResponse.class))
            }),
            @ApiResponse(responseCode = "400", description = "Invalid request", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "409", description = "Customer already exists", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = CustomersApi.PATH_CREATE_CUSTOMER,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default Mono<ResponseEntity<CustomerResponse>> createCustomer(
        @Parameter(name = "CustomerRequest", description = "", required = true) @Valid @RequestBody Mono<CustomerRequest> customerRequest,
        @Parameter(hidden = true) final ServerWebExchange exchange
    ) {
        Mono<Void> result = Mono.empty();
        exchange.getResponse().setStatusCode(HttpStatus.NOT_IMPLEMENTED);
        for (MediaType mediaType : exchange.getRequest().getHeaders().getAccept()) {
            if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                String exampleString = "{ \"identification\" : \"identification\", \"address\" : \"address\", \"gender\" : \"gender\", \"phone\" : \"phone\", \"name\" : \"name\", \"id\" : \"c123\", \"status\" : true }";
                result = ApiUtil.getExampleResponse(exchange, MediaType.valueOf("application/json"), exampleString);
                break;
            }
            if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                String exampleString = "{ \"code\" : \"RESOURCE_NOT_FOUND\", \"message\" : \"Resource not found\", \"timestamp\" : \"2000-01-23T04:56:07.000+00:00\" }";
                result = ApiUtil.getExampleResponse(exchange, MediaType.valueOf("application/json"), exampleString);
                break;
            }
            if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                String exampleString = "{ \"code\" : \"RESOURCE_NOT_FOUND\", \"message\" : \"Resource not found\", \"timestamp\" : \"2000-01-23T04:56:07.000+00:00\" }";
                result = ApiUtil.getExampleResponse(exchange, MediaType.valueOf("application/json"), exampleString);
                break;
            }
        }
        return result.then(customerRequest).then(Mono.empty());

    }


    String PATH_DELETE_CUSTOMER = "/api/v1/customers/{customerId}";
    /**
     * DELETE /api/v1/customers/{customerId} : Delete customer
     *
     * @param customerId  (required)
     * @return Customer deleted successfully (status code 204)
     */
    @Operation(
        operationId = "deleteCustomer",
        summary = "Delete customer",
        tags = { "Customers" },
        responses = {
            @ApiResponse(responseCode = "204", description = "Customer deleted successfully")
        }
    )
    @RequestMapping(
        method = RequestMethod.DELETE,
        value = CustomersApi.PATH_DELETE_CUSTOMER
    )
    default Mono<ResponseEntity<Void>> deleteCustomer(
        @NotNull @Parameter(name = "customerId", description = "", required = true, in = ParameterIn.PATH) @PathVariable("customerId") String customerId,
        @Parameter(hidden = true) final ServerWebExchange exchange
    ) {
        Mono<Void> result = Mono.empty();
        exchange.getResponse().setStatusCode(HttpStatus.NOT_IMPLEMENTED);
        return result.then(Mono.empty());

    }


    String PATH_GET_ALL_CUSTOMERS = "/api/v1/customers";
    /**
     * GET /api/v1/customers : Get all customers
     *
     * @return List of customers (status code 200)
     */
    @Operation(
        operationId = "getAllCustomers",
        summary = "Get all customers",
        tags = { "Customers" },
        responses = {
            @ApiResponse(responseCode = "200", description = "List of customers", content = {
                @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = CustomerResponse.class)))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = CustomersApi.PATH_GET_ALL_CUSTOMERS,
        produces = { "application/json" }
    )
    default Mono<ResponseEntity<Flux<CustomerResponse>>> getAllCustomers(
        @Parameter(hidden = true) final ServerWebExchange exchange
    ) {
        Mono<Void> result = Mono.empty();
        exchange.getResponse().setStatusCode(HttpStatus.NOT_IMPLEMENTED);
        for (MediaType mediaType : exchange.getRequest().getHeaders().getAccept()) {
            if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                String exampleString = "[ { \"identification\" : \"identification\", \"address\" : \"address\", \"gender\" : \"gender\", \"phone\" : \"phone\", \"name\" : \"name\", \"id\" : \"c123\", \"status\" : true }, { \"identification\" : \"identification\", \"address\" : \"address\", \"gender\" : \"gender\", \"phone\" : \"phone\", \"name\" : \"name\", \"id\" : \"c123\", \"status\" : true } ]";
                result = ApiUtil.getExampleResponse(exchange, MediaType.valueOf("application/json"), exampleString);
                break;
            }
        }
        return result.then(Mono.empty());

    }


    String PATH_GET_CUSTOMER_BY_ID = "/api/v1/customers/{customerId}";
    /**
     * GET /api/v1/customers/{customerId} : Get customer by ID
     *
     * @param customerId  (required)
     * @return Customer found (status code 200)
     *         or Customer not found (status code 404)
     */
    @Operation(
        operationId = "getCustomerById",
        summary = "Get customer by ID",
        tags = { "Customers" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Customer found", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = CustomerResponse.class))
            }),
            @ApiResponse(responseCode = "404", description = "Customer not found", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = CustomersApi.PATH_GET_CUSTOMER_BY_ID,
        produces = { "application/json" }
    )
    default Mono<ResponseEntity<CustomerResponse>> getCustomerById(
        @NotNull @Parameter(name = "customerId", description = "", required = true, in = ParameterIn.PATH) @PathVariable("customerId") String customerId,
        @Parameter(hidden = true) final ServerWebExchange exchange
    ) {
        Mono<Void> result = Mono.empty();
        exchange.getResponse().setStatusCode(HttpStatus.NOT_IMPLEMENTED);
        for (MediaType mediaType : exchange.getRequest().getHeaders().getAccept()) {
            if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                String exampleString = "{ \"identification\" : \"identification\", \"address\" : \"address\", \"gender\" : \"gender\", \"phone\" : \"phone\", \"name\" : \"name\", \"id\" : \"c123\", \"status\" : true }";
                result = ApiUtil.getExampleResponse(exchange, MediaType.valueOf("application/json"), exampleString);
                break;
            }
            if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                String exampleString = "{ \"code\" : \"RESOURCE_NOT_FOUND\", \"message\" : \"Resource not found\", \"timestamp\" : \"2000-01-23T04:56:07.000+00:00\" }";
                result = ApiUtil.getExampleResponse(exchange, MediaType.valueOf("application/json"), exampleString);
                break;
            }
        }
        return result.then(Mono.empty());

    }


    String PATH_UPDATE_CUSTOMER = "/api/v1/customers/{customerId}";
    /**
     * PUT /api/v1/customers/{customerId} : Update customer
     *
     * @param customerId  (required)
     * @param customerRequest  (required)
     * @return Customer updated (status code 200)
     *         or Customer not found (status code 404)
     */
    @Operation(
        operationId = "updateCustomer",
        summary = "Update customer",
        tags = { "Customers" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Customer updated", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = CustomerResponse.class))
            }),
            @ApiResponse(responseCode = "404", description = "Customer not found", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.PUT,
        value = CustomersApi.PATH_UPDATE_CUSTOMER,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default Mono<ResponseEntity<CustomerResponse>> updateCustomer(
        @NotNull @Parameter(name = "customerId", description = "", required = true, in = ParameterIn.PATH) @PathVariable("customerId") String customerId,
        @Parameter(name = "CustomerRequest", description = "", required = true) @Valid @RequestBody Mono<CustomerRequest> customerRequest,
        @Parameter(hidden = true) final ServerWebExchange exchange
    ) {
        Mono<Void> result = Mono.empty();
        exchange.getResponse().setStatusCode(HttpStatus.NOT_IMPLEMENTED);
        for (MediaType mediaType : exchange.getRequest().getHeaders().getAccept()) {
            if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                String exampleString = "{ \"identification\" : \"identification\", \"address\" : \"address\", \"gender\" : \"gender\", \"phone\" : \"phone\", \"name\" : \"name\", \"id\" : \"c123\", \"status\" : true }";
                result = ApiUtil.getExampleResponse(exchange, MediaType.valueOf("application/json"), exampleString);
                break;
            }
            if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                String exampleString = "{ \"code\" : \"RESOURCE_NOT_FOUND\", \"message\" : \"Resource not found\", \"timestamp\" : \"2000-01-23T04:56:07.000+00:00\" }";
                result = ApiUtil.getExampleResponse(exchange, MediaType.valueOf("application/json"), exampleString);
                break;
            }
        }
        return result.then(customerRequest).then(Mono.empty());

    }

}
