/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.19.0-SNAPSHOT).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.api;

import org.springframework.format.annotation.DateTimeFormat;
import org.openapitools.model.ErrorResponse;
import java.time.LocalDate;
import org.openapitools.model.MovementRequest;
import org.openapitools.model.MovementResponse;
import org.springframework.lang.Nullable;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.ExampleObject;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.multipart.MultipartFile;
import org.springframework.web.server.ServerWebExchange;
import reactor.core.publisher.Flux;
import reactor.core.publisher.Mono;
import org.springframework.http.codec.multipart.Part;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2026-01-07T05:45:55.296827463Z[Etc/UTC]", comments = "Generator version: 7.19.0-SNAPSHOT")
@Validated
@Tag(name = "Movements", description = "Account movement operations")
public interface MovementsApi {

    String PATH_CREATE_MOVEMENT = "/api/v1/accounts/{accountId}/movements";
    /**
     * POST /api/v1/accounts/{accountId}/movements : Register a movement for an account
     *
     * @param accountId  (required)
     * @param movementRequest  (required)
     * @return Movement registered successfully (status code 201)
     *         or Invalid movement (status code 400)
     *         or Account not found (status code 404)
     */
    @Operation(
        operationId = "createMovement",
        summary = "Register a movement for an account",
        tags = { "Movements" },
        responses = {
            @ApiResponse(responseCode = "201", description = "Movement registered successfully", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = MovementResponse.class))
            }),
            @ApiResponse(responseCode = "400", description = "Invalid movement", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "404", description = "Account not found", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = MovementsApi.PATH_CREATE_MOVEMENT,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default Mono<ResponseEntity<MovementResponse>> createMovement(
        @NotNull @Parameter(name = "accountId", description = "", required = true, in = ParameterIn.PATH) @PathVariable("accountId") String accountId,
        @Parameter(name = "MovementRequest", description = "", required = true) @Valid @RequestBody Mono<MovementRequest> movementRequest,
        @Parameter(hidden = true) final ServerWebExchange exchange
    ) {
        Mono<Void> result = Mono.empty();
        exchange.getResponse().setStatusCode(HttpStatus.NOT_IMPLEMENTED);
        for (MediaType mediaType : exchange.getRequest().getHeaders().getAccept()) {
            if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                String exampleString = "{ \"accountId\" : \"a123\", \"createdAt\" : \"2000-01-23T04:56:07.000+00:00\", \"amount\" : 150.75, \"description\" : \"description\", \"balanceAfter\" : 1049.25, \"id\" : \"m123\", \"type\" : \"DEBIT\" }";
                result = ApiUtil.getExampleResponse(exchange, MediaType.valueOf("application/json"), exampleString);
                break;
            }
            if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                String exampleString = "{ \"code\" : \"RESOURCE_NOT_FOUND\", \"message\" : \"Resource not found\", \"timestamp\" : \"2000-01-23T04:56:07.000+00:00\" }";
                result = ApiUtil.getExampleResponse(exchange, MediaType.valueOf("application/json"), exampleString);
                break;
            }
            if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                String exampleString = "{ \"code\" : \"RESOURCE_NOT_FOUND\", \"message\" : \"Resource not found\", \"timestamp\" : \"2000-01-23T04:56:07.000+00:00\" }";
                result = ApiUtil.getExampleResponse(exchange, MediaType.valueOf("application/json"), exampleString);
                break;
            }
        }
        return result.then(movementRequest).then(Mono.empty());

    }


    String PATH_GET_MOVEMENTS_BY_ACCOUNT = "/api/v1/accounts/{accountId}/movements";
    /**
     * GET /api/v1/accounts/{accountId}/movements : Get all movements for an account
     *
     * @param accountId  (required)
     * @param fromDate  (optional)
     * @param toDate  (optional)
     * @return List of movements (status code 200)
     */
    @Operation(
        operationId = "getMovementsByAccount",
        summary = "Get all movements for an account",
        tags = { "Movements" },
        responses = {
            @ApiResponse(responseCode = "200", description = "List of movements", content = {
                @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = MovementResponse.class)))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = MovementsApi.PATH_GET_MOVEMENTS_BY_ACCOUNT,
        produces = { "application/json" }
    )
    default Mono<ResponseEntity<Flux<MovementResponse>>> getMovementsByAccount(
        @NotNull @Parameter(name = "accountId", description = "", required = true, in = ParameterIn.PATH) @PathVariable("accountId") String accountId,
        @Parameter(name = "fromDate", description = "", in = ParameterIn.QUERY) @Valid @RequestParam(value = "fromDate", required = false) @DateTimeFormat(iso = DateTimeFormat.ISO.DATE) @Nullable LocalDate fromDate,
        @Parameter(name = "toDate", description = "", in = ParameterIn.QUERY) @Valid @RequestParam(value = "toDate", required = false) @DateTimeFormat(iso = DateTimeFormat.ISO.DATE) @Nullable LocalDate toDate,
        @Parameter(hidden = true) final ServerWebExchange exchange
    ) {
        Mono<Void> result = Mono.empty();
        exchange.getResponse().setStatusCode(HttpStatus.NOT_IMPLEMENTED);
        for (MediaType mediaType : exchange.getRequest().getHeaders().getAccept()) {
            if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                String exampleString = "[ { \"accountId\" : \"a123\", \"createdAt\" : \"2000-01-23T04:56:07.000+00:00\", \"amount\" : 150.75, \"description\" : \"description\", \"balanceAfter\" : 1049.25, \"id\" : \"m123\", \"type\" : \"DEBIT\" }, { \"accountId\" : \"a123\", \"createdAt\" : \"2000-01-23T04:56:07.000+00:00\", \"amount\" : 150.75, \"description\" : \"description\", \"balanceAfter\" : 1049.25, \"id\" : \"m123\", \"type\" : \"DEBIT\" } ]";
                result = ApiUtil.getExampleResponse(exchange, MediaType.valueOf("application/json"), exampleString);
                break;
            }
        }
        return result.then(Mono.empty());

    }

}
