package com.ntt.banking.domain.movement;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.Objects;

public class Movement {
    private final String id;
    private final LocalDateTime dateTime;
    private final String type; // DEBIT, CREDIT
    private final BigDecimal amount;
    private final BigDecimal balance;
    private final String description;
    private final String accountId;

    public Movement(
            String id,
            LocalDateTime dateTime,
            String type,
            BigDecimal amount,
            BigDecimal balance,
            String description,
            String accountId) {
        this.id = id;
        this.dateTime = Objects.requireNonNull(dateTime);
        this.type = Objects.requireNonNull(type);
        this.amount = Objects.requireNonNull(amount);
        this.balance = Objects.requireNonNull(balance);
        this.description = description;
        this.accountId = Objects.requireNonNull(accountId);
    }

    public static Movement create(String type, BigDecimal amount, BigDecimal balance, String description,
            String accountId) {
        return new Movement(
                null, // ID generated by DB
                LocalDateTime.now(),
                type,
                amount,
                balance,
                description,
                accountId);
    }

    public String getId() {
        return id;
    }

    public LocalDateTime getDateTime() {
        return dateTime;
    }

    public String getType() {
        return type;
    }

    public BigDecimal getAmount() {
        return amount;
    }

    public BigDecimal getBalance() {
        return balance;
    }

    public String getDescription() {
        return description;
    }

    public String getAccountId() {
        return accountId;
    }
}
